# Docker compose file for MissionControlDatabase

# Command to set up the MissionControlDatabase container
# docker compose -f docker-compose.yml up -d

name: "missioncontroldatabase"
version: "3.1"

services:
  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=lprd
      - POSTGRES_PASSWORD=tyJcV9oY1wvZU9IPpGgD
      - POSTGRES_DB=missioncontroldb
    ports:
      - 5432:5432
    volumes:
      - missioncontrol-db:/var/lib/postgresql/data

volumes:
  missioncontrol-db: