# Docker compose file for MissionControlServer

# Command to set up the MissionControlServer container
# docker compose -f docker-compose.yml up -d

name: "missioncontrolserver"
version: "3.1"

services:
  MissionControlServer:
    image: debian:trixie
    restart: always
    environment:
      - DATABASE_USER=lprd
      - DATABASE_PASS=tyJcV9oY1wvZU9IPpGgD
      - DATABASE_NAME=missioncontroldb
      - DATABASE_HOST=database
    tty: true
    network_mode: "missioncontrolnet"

    command: bash -c "
        if [ -d /home/MissionControl/ ]; then
          echo 'MissionControl available!';
        else
          echo 'Getting MissionControl!';
          apt update -y && apt upgrade -y;
          apt-get install git -y;
          cd /home;
          git clone https://github.com/LPRD/MissionControl.git;
          cd /home/MissionControl/Server/MissionControlServer;
          ./setup.sh;
        fi;
        if [ -d /home/MissionControl/Server/MissionControlServer/output ]; then
          echo 'starting MissionControlServer!';
          cd /home/MissionControl/Server/MissionControlServer;
          ./run.sh;
        else
          echo 'executing default \"bash\" command!';
          bash;
        fi;"
    ports:
        - 13056:13056
    # volumes:
    #   - import:/opt/app/import

# volumes:
#   import:
